import type { LoginResponse } from '@/types/auth';
import type { LoanProduct, SavingsProduct } from '@/types/products';
import type { UserProfile } from '@/types/user';

export const SESSION: LoginResponse = {
  accessToken: 'test-access-token',
  expiresIn: 900,
  user: { id: '123', name: 'John Doe', email: 'john@example.com' },
};

export const PROFILE: UserProfile = {
  ...SESSION.user,
  phone: '0801****678',
  tier: 'Premium',
  memberSince: '2022-03-14',
  accountNumberMasked: '******6789',
  bvnMasked: '********901',
};

export const SAVINGS_PRODUCTS: SavingsProduct[] = [
  {
    id: '1',
    name: 'Target Savings',
    interestRate: 12,
    minimumAmount: 5000,
    maximumAmount: 50_000_000,
    duration: '12 months',
    description: 'Save towards a specific financial goal.',
    longDescription: 'Set a goal and automate contributions towards it.',
    icon: 'target',
    currency: 'NGN',
    features: ['Automated contributions', 'Goal tracking'],
    terms: ['Minimum contribution of NGN 5,000.'],
  },
  {
    id: '2',
    name: 'Flexible Savings',
    interestRate: 8,
    minimumAmount: 1000,
    maximumAmount: null,
    duration: 'Flexible',
    description: 'Save and withdraw whenever you like.',
    longDescription: 'A high-yield everyday savings account with no lock-in.',
    icon: 'flex',
    currency: 'NGN',
    features: ['Withdraw any time'],
    terms: ['Minimum opening deposit of NGN 1,000.'],
  },
  {
    id: '3',
    name: 'Fixed Savings',
    interestRate: 18,
    minimumAmount: 100_000,
    maximumAmount: 100_000_000,
    duration: '6 months',
    description: 'Lock a lump sum for six months.',
    longDescription: 'Lock in a lump sum for six months at a guaranteed rate.',
    icon: 'lock',
    currency: 'NGN',
    features: ['Guaranteed rate'],
    terms: ['Funds are locked for 6 months.'],
  },
];

export const LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: '1',
    name: 'Personal Loan',
    minAmount: 50_000,
    maxAmount: 2_000_000,
    interestRate: 5,
    interestLabel: '5% monthly',
    tenure: '3-12 months',
    description: 'Quick cash for life’s moments.',
    longDescription: 'Up to NGN 2,000,000 with a repayment plan that fits your income.',
    icon: 'person',
    currency: 'NGN',
    disbursement: 'Within 24 hours of approval',
    eligibility: ['Aged 21-60', 'Verified BVN'],
    requirements: ['Six months of bank statements'],
  },
  {
    id: '2',
    name: 'Salary Advance',
    minAmount: 50_000,
    maxAmount: 500_000,
    interestRate: 4,
    interestLabel: '4% monthly',
    tenure: '1-3 months',
    description: 'Access up to 50% of your next salary.',
    longDescription: 'Bridge the gap to payday.',
    icon: 'salary',
    currency: 'NGN',
    disbursement: 'Instant',
    eligibility: ['Salaried customer'],
    requirements: ['Payslip'],
  },
  {
    id: '3',
    name: 'Business Loan',
    minAmount: 500_000,
    maxAmount: 10_000_000,
    interestRate: null,
    interestLabel: 'Based on assessment',
    tenure: '6-24 months',
    description: 'Working capital for registered SMEs.',
    longDescription: 'Fund inventory, equipment or expansion.',
    icon: 'business',
    currency: 'NGN',
    disbursement: '3-5 working days',
    eligibility: ['Registered with the CAC'],
    requirements: ['CAC documents'],
  },
];
